version: "3.8"
services:
  web:
    container_name: fast_api_web
    depends_on:
      - db
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/proj
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --reload

  db:
    image: postgres:11
    container_name: fast_api_postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./.env
